#[build options]
cache=local
db=postgres
transaction-xa-enabled=true
features=
http-relative-path=
health-enabled=false
metrics-enabled=false

#[runtime options]
db-url=jdbc:postgresql://172.18.26.1/keycloak
db-username=postgres
db-password=

log=console
log-console-color=false
log-console-format=[%d{yyyy-MM-dd HH:mm:ss,SSSz}][%-5p][%c{3.}] (%t) %s%e%n

proxy=none
http-enabled=true
http-port=8080
hostname-strict=false
hostname-strict-https=false


#[email-sender-provider:opfa-cid-embedding]
#spi-email-sender-provider=opfa-cid-embedding

#[events-listener:opfa-login-stats]
#spi-events-listener-opfa-login-stats-attribute=loginStats

