#[build options]
cache=local
db=postgres
transaction-xa-enabled=true
features=update-email
http-relative-path=/
health-enabled=true
metrics-enabled=true

#[runtime options]
db-url=jdbc:postgresql://172.18.26.3/keycloak
db-username=postgres
db-password=

log=console
log-console-format=[%d{yyyy-MM-dd HH:mm:ss,SSSz}][%-5p][%c{3.}] (%t) %s%e%n

proxy=none
http-enabled=true
http-port=8080
hostname-strict=false
hostname-strict-https=false


#[email-sender-provider:opfa-cid-embedding]
#spi-email-sender-provider=opfa-cid-embedding

#[events-listener:opfa-login-stats]
#spi-events-listener-opfa-login-stats-attribute=loginStats


#[theme-welcome-theme:opfablank]
spi-theme-welcome-theme=opfablank


#[opfa-sms-client:opfa-sms-client-configurable]
#spi-opfa-sms-client-opfa-sms-client-configurable-client-id=CID
#spi-opfa-sms-client-opfa-sms-client-configurable-client-secret=CSEC
#spi-opfa-sms-client-opfa-sms-client-configurable-region=eu-west-1
#spi-opfa-sms-client-opfa-sms-client-configurable-sender-id=SENDER

#[opfa-sms-otp:opfa-sms-otp-expiring]
#spi-opfa-sms-otp-opfa-sms-otp-expiring-duration=PT99H
#spi-opfa-sms-otp-opfa-sms-otp-expiring-max-tentatives=7
#spi-opfa-sms-otp-opfa-sms-otp-expiring-gen-mode=RANDOM
#spi-opfa-sms-otp-opfa-sms-otp-expiring-preset=99999

#[authenticator:opfa-sms-otp-authenticator]
#spi-authenticator-opfa-sms-otp-authenticator-user-mobile-attribute=mobile
#spi-authenticator-opfa-sms-otp-authenticator-auth-note-mobile-attribute=mobile


#[cookie:site-local-as-secure]
spi-cookie-provider=site-local-as-secure
