<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.optionfactory.keycloak</groupId>
        <artifactId>optionfactory-keycloak</artifactId>
        <version>2.3</version>
    </parent>
    <artifactId>optionfactory-keycloak-sms</artifactId>
    <description>optionfactory-keycloak-aws-sms</description>
    <name>net.optionfactory.keycloak:optionfactory-keycloak-sms</name>
    <packaging>jar</packaging>
    <dependencies>  
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi-private</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-services</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sns</artifactId>
            <version>2.20.22</version>
        </dependency>
                
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                                    <resources>
                                        <resource>META-INF/MANIFEST.MF</resource>
                                        <resource>META-INF/LICENSE.txt</resource>
                                        <resource>META-INF/LICENSE</resource>
                                        <resource>META-INF/NOTICE.txt</resource>
                                        <resource>META-INF/NOTICE</resource>
                                        <resource>META-INF/DEPENDENCIES</resource>
                                    </resources>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.properties.PropertiesTransformer">
                                    <resource>META-INF/io.netty.versions.properties</resource>
                                    <ordinalKey>ordinal</ordinalKey>
                                </transformer>
                            </transformers>
                            <relocations>
                                <relocation>
                                    <pattern>VersionInfo.java</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.org</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.slf4j</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.org.slf4j</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.reactivestreams</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.org.reactivestreams</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.org.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>software</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.software</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.netty</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.sms.shaded.io.netty</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>    
    </build>        
</project>
