<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.optionfactory.keycloak</groupId>
        <artifactId>optionfactory-keycloak</artifactId>
        <version>1.8</version>
    </parent>
    <artifactId>optionfactory-keycloak-validation</artifactId>
    <description>optionfactory-keycloak validation</description>
    <name>${project.groupId}:${project.artifactId}</name>
    <packaging>jar</packaging>
    <dependencies>  
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-services</artifactId>
            <scope>provided</scope>
        </dependency>
                
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>6.2.3.Final</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.logging</groupId>
                    <artifactId>jboss-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>        
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>jakarta.el</artifactId>
            <version>3.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
<!--                                <relocation>
                                    <pattern>org.hibernate.validator</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.validation.shade.hibernate.validator</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>javax.validation</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.validation.shade.javax.validation</shadedPattern>
                                </relocation>-->
                                <relocation>
                                    <pattern>com.fasterxml.classmate</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.validation.shade.fasterxml.classmate</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.sun.el</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.validation.shade.com.sun.el</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>javax.el</pattern>
                                    <shadedPattern>net.optionfactory.keycloak.validation.shade.javax.el</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>    
    </build>        
</project>
